pipeline {
    agent any
    stages {
            stage ('clean up') {
	        steps {
	            cleanWs()
	        }
	    }         
      stage('Clone sources') {
            steps {
                sh 'git clone https://github.com/aklot07/Amazon'
            }
        }
	    stage('Build jar') {
		    steps {
			    dir ('Amazon/Amazon/Amazon-core'){
				    sh 'mvn clean package'
			    }
		    }
	    }	    
      stage('SonarQube analysis') {
            steps {
		   dir ('Amazon/Amazon/Amazon-web'){ 
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn clean package sonar:sonar'
			              }
                   }
               }
           }         
        }
    }
